name: snipvid
description: "Montage photo vers vidéo automatique"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Navigation
  go_router: ^14.0.0
  
  # State management
  provider: ^6.1.0
  
  # Media
  image_picker: ^1.0.0
  photo_manager: ^3.0.0
  video_player: ^2.8.0
  audioplayers: ^6.0.0
  
  # FFmpeg pour le montage vidéo
  ffmpeg_kit_flutter: ^6.0.3
  
  # Storage
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  
  # HTTP (pour Pixabay API)
  http: ^1.2.0
  
  # Utils
  uuid: ^4.3.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
